/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form.attribute;

import com.raven.form.SanPham;
import com.raven.services.HeDieuHanhService;
import com.raven.services.impl.HeDieuHanhServiceImpl;
import com.raven.viewmodels.HeDieuHanhResponse;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class HeDieuHanhDialog extends javax.swing.JDialog {

    /**
     * Creates new form HeDieuHanhDialog
     */
    SanPham product = new SanPham();
    DefaultTableModel dtm = new DefaultTableModel();
    private HeDieuHanhService service = new HeDieuHanhServiceImpl();

    public HeDieuHanhDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm = (DefaultTableModel) tableHeDieuHanh.getModel();
        showData(service.getTenHeDieuHanh());

    }

    void showData(List<HeDieuHanhResponse> listHDH) {
        dtm.setRowCount(0);
        for (HeDieuHanhResponse hdh : listHDH) {
            dtm.addRow(new Object[]{
                hdh.getId(), hdh.getHeDieuHanh()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHeDieuHanh = new javax.swing.JTable();
        btnThemHDH = new javax.swing.JButton();
        btnSuaHDH = new javax.swing.JButton();
        btnLamMoiHDH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaHdh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHdh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableHeDieuHanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuộc tính", "Tên thuộc tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHeDieuHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHeDieuHanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHeDieuHanh);

        btnThemHDH.setText("Thêm");
        btnThemHDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDHActionPerformed(evt);
            }
        });

        btnSuaHDH.setText("Sửa");
        btnSuaHDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHDHActionPerformed(evt);
            }
        });

        btnLamMoiHDH.setText("Làm mới");
        btnLamMoiHDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiHDHActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã thuộc tính");

        txtMaHdh.setEnabled(false);

        jLabel2.setText("Tên thuộc tính");

        txtTenHdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHdhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hệ điều hành");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHdh)
                            .addComponent(txtTenHdh, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnThemHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(btnLamMoiHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(162, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHDH)
                    .addComponent(btnSuaHDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoiHDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
HeDieuHanhResponse getForm() {
        String ten = txtTenHdh.getText();
        return new HeDieuHanhResponse(ten);
    }
    private void btnThemHDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDHActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            String ten = txtTenHdh.getText();
            if (isHeDieuHanhExisted(ten)) {
                JOptionPane.showMessageDialog(this, "Tên thuộc tính đã tồn tại");
                return;
            }
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?") == 0) {
                HeDieuHanhResponse hdh = getForm();
                if (service.add(hdh)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    showData(service.getAll());
                    product.showHeDieuHanh(service.getTenHeDieuHanh());
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnThemHDHActionPerformed
    public Boolean isHeDieuHanhExisted(String tenThuocTinh) {
        for (HeDieuHanhResponse exhdh : service.getTenHeDieuHanh()) {
            if (tenThuocTinh.equals(exhdh.getHeDieuHanh())) {
                return true;
            }
        }
        return false;
    }

    boolean validateForm() {
        if (txtTenHdh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn cần nhập tên hệ điều hành");
            return false;
        }
        if (!txtTenHdh.getText().matches("[a-zA-Z0-9\\sàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễđòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳỹỷýÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄĐÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲỸỶÝ]+")) {
            JOptionPane.showMessageDialog(this, "Tên hệ điều hành chỉ được chứa số, chữ và khoảng trắng");
            return false;
        }
        return true;
    }
    private void btnLamMoiHDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiHDHActionPerformed
        // TODO add your handling code here:
        txtTenHdh.setText("");
        txtMaHdh.setText("");
    }//GEN-LAST:event_btnLamMoiHDHActionPerformed

    private void txtTenHdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHdhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenHdhActionPerformed
    void setForm(HeDieuHanhResponse hdhr) {
        txtMaHdh.setText(hdhr.getId() + "");
        txtTenHdh.setText(hdhr.getHeDieuHanh() + "");
    }
    private void tableHeDieuHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHeDieuHanhMouseClicked
        // TODO add your handling code here:
        int row = tableHeDieuHanh.getSelectedRow();
        HeDieuHanhResponse kh = service.getAll().get(row);
        setForm(kh);
    }//GEN-LAST:event_tableHeDieuHanhMouseClicked

    private void btnSuaHDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHDHActionPerformed
        // TODO add your handling code here:
        int row = tableHeDieuHanh.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 dòng");
            return;
        }
        if (validateForm()) {
            for (HeDieuHanhResponse dl : service.getAll()) {
                if (!dl.getHeDieuHanh().equals(txtTenHdh.getText()) && String.valueOf(dl.getId()).equals(txtMaHdh.getText())) {
                    JOptionPane.showMessageDialog(this, "Tên hệ điều hành này đã tồn tại bạn có thể sử dụng lại");
                    return;
                }
            }
            int ma = (int) tableHeDieuHanh.getValueAt(row, 0);
            HeDieuHanhResponse kh = getForm();
            if (service.update(kh, ma)) {
                JOptionPane.showMessageDialog(this, "Thành công");
                showData(service.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaHDHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeDieuHanhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeDieuHanhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeDieuHanhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeDieuHanhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HeDieuHanhDialog dialog = new HeDieuHanhDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiHDH;
    private javax.swing.JButton btnSuaHDH;
    private javax.swing.JButton btnThemHDH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHeDieuHanh;
    private javax.swing.JTextField txtMaHdh;
    private javax.swing.JTextField txtTenHdh;
    // End of variables declaration//GEN-END:variables

}
