/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form.attribute;

import com.raven.form.SanPham;
import com.raven.services.ManHinhService;
import com.raven.services.impl.GpuServiceImpl;
import com.raven.services.impl.ManHinhServiceImpl;
import com.raven.viewmodels.GpuResponse;
import com.raven.viewmodels.ManHinhResponse;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.jfr.consumer.EventStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author nguye
 */
public class ManHinhDialog extends javax.swing.JDialog {

    /**
     * Creates new form ManHinhDialog
     */
    SanPham product = new SanPham();
    DefaultTableModel dtm = new DefaultTableModel();
    private ManHinhService service = new ManHinhServiceImpl();

    public ManHinhDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm = (DefaultTableModel) tableManHinh.getModel();
        showData(service.getLoaiManHinh());
    }

    void showData(List<ManHinhResponse> mhr) {
        dtm.setRowCount(0);
        for (ManHinhResponse mh : mhr) {
            dtm.addRow(new Object[]{
                mh.getId(), mh.getLoaiManHinh()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableManHinh = new javax.swing.JTable();
        btnThemManHinh = new javax.swing.JButton();
        btnSuaManHinh = new javax.swing.JButton();
        btnLamMoiMH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaMh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenMh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableManHinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuộc tính", "Tên thuộc tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableManHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableManHinhMouseClicked(evt);
            }
        });
        tableManHinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableManHinhKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableManHinh);

        btnThemManHinh.setText("Thêm");
        btnThemManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemManHinhActionPerformed(evt);
            }
        });

        btnSuaManHinh.setText("Sửa");
        btnSuaManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaManHinhActionPerformed(evt);
            }
        });

        btnLamMoiMH.setText("Làm mới");
        btnLamMoiMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiMHActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã thuộc tính");

        txtMaMh.setEnabled(false);

        jLabel2.setText("Tên thuộc tính");

        txtTenMh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Màn hình");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaMh)
                            .addComponent(txtTenMh, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnThemManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(btnLamMoiMH, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(175, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemManHinh)
                    .addComponent(btnSuaManHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoiMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemManHinhActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            String ten = txtTenMh.getText();
            if (isManHinhExisted(ten)) {
                JOptionPane.showMessageDialog(this, "Tên thuộc tính đã tồn tại");
                return;
            }
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?") == 0) {
                ManHinhResponse mhr = getForm();
                if (service.add(mhr)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    showData(service.getAll());
                    product.showManHinh(service.getLoaiManHinh());
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }

            }
        }
    }//GEN-LAST:event_btnThemManHinhActionPerformed
    public Boolean isManHinhExisted(String tenThuocTinh) {
        for (ManHinhResponse exmh : service.getLoaiManHinh()) {
            if (tenThuocTinh.equals(exmh.getLoaiManHinh())) {
                return true;
            }
        }
        return false;
    }

    boolean validateForm() {
        if (txtTenMh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn cần nhập tên màn hình");
            return false;
        }
        if (!txtTenMh.getText().matches("[a-zA-Z0-9\\sàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễđòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳỹỷýÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄĐÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲỸỶÝ]+")) {
            JOptionPane.showMessageDialog(this, "Tên màn hình chỉ được chứa số, chữ và khoảng trắng");
            return false;
        }
        return true;
    }
    private void btnLamMoiMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiMHActionPerformed
        // TODO add your handling code here:
        txtMaMh.setText("");
        txtTenMh.setText("");
    }//GEN-LAST:event_btnLamMoiMHActionPerformed

    private void txtTenMhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMhActionPerformed

    private void tableManHinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableManHinhKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableManHinhKeyPressed
    void setForm(ManHinhResponse mhr) {
        txtMaMh.setText(mhr.getId() + "");
        txtTenMh.setText(mhr.getLoaiManHinh() + "");
    }
    private void tableManHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableManHinhMouseClicked
        // TODO add your handling code here:
        int row = tableManHinh.getSelectedRow();
        ManHinhResponse mh = service.getAll().get(row);
        setForm(mh);
    }//GEN-LAST:event_tableManHinhMouseClicked

    private void btnSuaManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaManHinhActionPerformed
        // TODO add your handling code here:
        int row = tableManHinh.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 dòng");
            return;
        }
        if (validateForm()) {
            for (ManHinhResponse dl : service.getAll()) {
                if (!dl.getLoaiManHinh().equals(txtTenMh.getText()) && String.valueOf(dl.getId()).equals(txtMaMh.getText())) {
                    JOptionPane.showMessageDialog(this, "Tên màn hình này đã tồn tại bạn có thể sử dụng lại");
                    return;
                }
            }
            int ma = (int) tableManHinh.getValueAt(row, 0);
            ManHinhResponse kh = getForm();
            if (service.update(kh, ma)) {
                JOptionPane.showMessageDialog(this, "Thành công");
                showData(service.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaManHinhActionPerformed
    ManHinhResponse getForm() {
        String ten = txtTenMh.getText();
        return new ManHinhResponse(ten);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManHinhDialog dialog = new ManHinhDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiMH;
    private javax.swing.JButton btnSuaManHinh;
    private javax.swing.JButton btnThemManHinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableManHinh;
    private javax.swing.JTextField txtMaMh;
    private javax.swing.JTextField txtTenMh;
    // End of variables declaration//GEN-END:variables
}
