/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form.attribute;

import com.raven.form.SanPham;
import com.raven.services.MauSacService;
import com.raven.services.RamService;
import com.raven.services.impl.MauSacServiceImpl;
import com.raven.services.impl.RamServiceImpl;
import com.raven.viewmodels.RamResponse;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.jfr.consumer.EventStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author nguye
 */
public class RamDialog extends javax.swing.JDialog {

    /**
     * Creates new form RamDialog
     */
    SanPham product = new SanPham();
    DefaultTableModel dtm = new DefaultTableModel();
    private RamService service = new RamServiceImpl();

    public RamDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm = (DefaultTableModel) tableRam.getModel();
        showDataRam(service.getDungLuongRam());
    }

    void showDataRam(List<RamResponse> listRam) {
        dtm.setRowCount(0);
        for (RamResponse rm : listRam) {
            dtm.addRow(new Object[]{
                rm.getId(), rm.getDungLuongRam()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRam = new javax.swing.JTable();
        btnThemRam = new javax.swing.JButton();
        btnSuaRam = new javax.swing.JButton();
        btnLamMoiRam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaRm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenRm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableRam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuộc tính", "Tên thuộc tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRam);

        btnThemRam.setText("Thêm");
        btnThemRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemRamActionPerformed(evt);
            }
        });

        btnSuaRam.setText("Sửa");
        btnSuaRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaRamActionPerformed(evt);
            }
        });

        btnLamMoiRam.setText("Làm mới");
        btnLamMoiRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiRamActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã thuộc tính");

        txtMaRm.setEnabled(false);

        jLabel2.setText("Tên thuộc tính");

        txtTenRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenRmActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ram");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaRm)
                                    .addComponent(txtTenRm, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnThemRam, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(btnSuaRam, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLamMoiRam, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemRam)
                    .addComponent(btnSuaRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoiRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemRamActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            String ten = txtTenRm.getText();
            if (isRamExisted(ten)) {
                JOptionPane.showMessageDialog(this, "Tên thuộc tính đã tồn tại");
                return;
            }
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?") == 0) {
                RamResponse gpu = getForm();
                if (service.add(gpu)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    showDataRam(service.getAll());
                    product.showRam(service.getDungLuongRam());
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnThemRamActionPerformed
    public Boolean isRamExisted(String tenThuocTinh) {
        for (RamResponse exrm : service.getDungLuongRam()) {
            if (tenThuocTinh.equals(exrm.getDungLuongRam())) {
                return true;
            }
        }
        return false;
    }

    boolean validateForm() {
        if (txtTenRm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn cần nhập tên ram");
            return false;
        }

        String regex = "^[0-9]+$";
        if (!txtTenRm.getText().matches(regex)) {
            JOptionPane.showMessageDialog(this, "Tên ram chỉ được chứa số");
            return false;
        }

        return true;
    }

    private void btnLamMoiRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiRamActionPerformed
        // TODO add your handling code here:
        txtTenRm.setText("");
        txtMaRm.setText("");
    }//GEN-LAST:event_btnLamMoiRamActionPerformed

    private void txtTenRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenRmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenRmActionPerformed
    void setForm(RamResponse rr) {
        txtMaRm.setText(rr.getId() + "");
        txtTenRm.setText(rr.getDungLuongRam() + "");
    }
    private void tableRamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRamMouseClicked
        // TODO add your handling code here:
        int row = tableRam.getSelectedRow();
        RamResponse kh = service.getAll().get(row);
        setForm(kh);
    }//GEN-LAST:event_tableRamMouseClicked

    private void btnSuaRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaRamActionPerformed
        // TODO add your handling code here:
        int row = tableRam.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 dòng");
            return;
        }
        if (validateForm()) {
            for (RamResponse dl : service.getAll()) {
                if (!dl.getDungLuongRam().equals(txtTenRm.getText()) && String.valueOf(dl.getId()).equals(txtMaRm.getText())) {
                    JOptionPane.showMessageDialog(this, "Tên ram này đã tồn tại bạn có thể sử dụng lại");
                    return;
                }
            }
            int ma = (int) tableRam.getValueAt(row, 0);
            RamResponse kh = getForm();
            if (service.update(kh, ma)) {
                JOptionPane.showMessageDialog(this, "Thành công");
                showDataRam(service.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaRamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RamDialog dialog = new RamDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiRam;
    private javax.swing.JButton btnSuaRam;
    private javax.swing.JButton btnThemRam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRam;
    private javax.swing.JTextField txtMaRm;
    private javax.swing.JTextField txtTenRm;
    // End of variables declaration//GEN-END:variables

    private RamResponse getForm() {
        String ten = txtTenRm.getText();
        return new RamResponse(ten);
    }

}
